export const OrderActions = {
  SET_ORDERS: 'SET_ORDERS',
  SET_ORDER: 'SET_ORDER',
  ADD_ORDER: 'ADD_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  RESET: 'RESET',
}
